DROP DATABASE IF EXISTS esercizio;
CREATE DATABASE esercizio;
USE esercizio;
CREATE TABLE esercizio (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);
DROP USER IF EXISTS 'user'@'10.10.20.10';
CREATE USER 'user'@'10.10.20.10' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON esercizio.* TO 'user'@'10.10.20.10';
FLUSH PRIVILEGES;